#!/usr/bin/env bash

# Copyright 2017 Heptio Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

main() {
    if [ -e "${HOME}/.kube/${1}" ];then
        echo "export KUBECONFIG=\"${HOME}/.kube/${1}\""
    else
    # We need to echo out an additional echo command so that when ktx is run through eval
    # the output is in the appropriate format to be sent to the console.
        echo "echo \"The following file does not exist: ${HOME}/.kube/${1}. Exiting...\""
    fi
}
main ${1}
